name: dice_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bot_toast: ^4.0.1
  cached_network_image: ^3.1.0+1
  camera: ^0.9.4+3
  circular_profile_avatar: ^2.0.5
  collection: ^1.15.0
  contacts_service: ^0.6.1
  country_code_picker: ^2.0.2
  country_list_pick: ^1.0.1+4
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  device_info: ^2.0.0
  dio: ^4.0.4
  draggable_bottom_sheet: ^0.1.2
  equatable: ^2.0.0
  event_bus: ^2.0.0
  exif: ^3.1.1
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  flick_video_player: ^0.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_image_compress: ^1.0.0
  flutter_local_notifications: ^9.1.4
  flutter_native_image: ^0.0.6+1
  flutter_native_splash: ^1.3.2
  flutter_screenutil: ^5.0.0
  flutter_slidable: ^0.6.0
  flutter_sms: ^2.3.2
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  get_it: ^7.1.3
  graphql_flutter: ^5.0.0-nullsafety.2
  grouped_list: ^4.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.3
  image_cropper: ^1.4.0
  image_picker: ^0.7.5
  injectable: ^1.4.0
  intl: null
  jiffy: ^5.0.0
  logger: ^1.1.0
  open_mail_app: ^0.4.3
  page_transition: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.6
  permission_handler: ^8.1.2
  phoenix_wings: ^1.0.2
  photo_manager: ^1.3.8
  pin_code_fields: ^7.1.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  slide_item: ^1.0.8
  timeago: ^3.2.1
  url_launcher: ^6.0.9
  video_player: ^2.2.18
  video_thumbnail: ^0.4.3
  visibility_detector: ^0.2.2

dev_dependencies:
  build_runner: ^2.0.3
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter
  injectable_generator: null
  phoenix_socket: ^0.5.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dice.png"
  remove_alpha: true

flutter_native_splash:
  image: "assets/logo.png"
  color: "#ffffff"
  color_dark: "#000000"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Objectivity
      fonts:
        - asset: assets/fonts/Objectivity-Black.otf
        - asset: assets/fonts/Objectivity-Bold.otf
          weight: 700
        - asset: assets/fonts/Objectivity-Light.otf
        - asset: assets/fonts/Objectivity-Medium.otf
          weight: 500
        - asset: assets/fonts/Objectivity-Regular.otf
          weight: 300
